### ISSUE TITLE
Attach APK to release?

### ISSUE THREAD

**Issue by IzzySoft** [benoitletondor/EasyBudget#1]
Hi Peter,

would you consider attaching the `.apk` file with your `releases/` here on Github – so people running Google-free devices w/o Playstore access can grab your app? I'd then even offer to [add it here](https://android.izzysoft.de/repo), so your users can get updates automatically using the F-Droid client.

Thanks in advance!

**Comment by benoitletondor** [comment]
Hello there,

Sorry for the delay. I attached the APK for the last release and will do so in the future, it's actually a good idea.

As for F-Droid, I'll pass on that since I'm not really interested in being listed in those kind of repo. I want PlayStore to be the only "officially supported" way to get the app.

Thanks

**Comment by IzzySoft** [comment]
First thanks! So just to make sure I understood you correctly: Would you answer the question on whether I may include your app in my repo with a "No" – or would it be OK for you if I include it? I hope for the latter. Just to resolve possible doubts: There are no extra steps involved for you. With the `.apk` attached to the releases here, I'd take care for the rest. No obligations for you :)

**Comment by benoitletondor** [comment]
Yes you read correctly, I don't wanna be listed in your F-Droid repo. 
I want PlayStore to stay the only way to get automatic updates and new features. If people want to have the APK without the PlayStore it's now available here, and it should be enough :)

**Comment by IzzySoft** [comment]
Not the answer I was hoping for, but I of course respect it. Thanks anyhow for making it available via the releases page :)
