### ISSUE TITLE
Frequently Asked Question (FAQ) Proposal 

### ISSUE THREAD

**Issue by hushbee** [benoitletondor/EasyBudget#11]
Hello there, I'd like to contribute to your awesome project by writing a Frequent Asked Questions for users self-service. Would love to hear from you, thanks.

**Comment by benoitletondor** [comment]
Hi @hushbee !

It's a great idea. I'd love to include that into the app. I'm not sure what to put into though. Do you have any idea?

As for the format, it could be an html file per language?

**Comment by hushbee** [comment]
Great, am thinking of writing it in markdown if that's a good idea

**Comment by benoitletondor** [comment]
That could work yes, would need to convert it to HTML to display it into the app but that's doable 👍

**Comment by hushbee** [comment]
Hey, I have finished working on the FAQ file and I've made a pull request 

Kindly merge.

**Comment by hushbee** [comment]
Hello there, I haven't seen you merge the FAQ yet, hope there's no problem
with it.
If there is any problem, lemme know ASAP.
