### ISSUE TITLE
A build operation failed.

### ISSUE THREAD

**Issue by ImadBL** [benoitletondor/EasyBudget#16]
Hi, 

can you help me to build this project:

i have this error: 

A build operation failed.
    Could not create task ':app:compileDebugJavaWithJavac'.
Could not create task ':app:compileDebugJavaWithJavac'.
Failed to calculate the value of task ':app:compileDebugJavaWithJavac' property 'javaCompiler'.
No matching toolchains found for requested specification: {languageVersion=11, vendor=any, implementation=vendor-specific}.
No locally installed toolchains match (see https://docs.gradle.org/8.1/userguide/toolchains.html#sec:auto_detection) and toolchain download repositories have not been configured (see https://docs.gradle.org/8.1/userguide/toolchains.html#sub:download_repositories).

**Comment by benoitletondor** [comment]
This is related to your setup, not this repo
