### ISSUE TITLE
Issue in importing project

### ISSUE THREAD

**Issue by srisk94** [benoitletondor/EasyBudget#2]
Error:(38, 0) Could not find property 'batch_devkey' on BuildType_Decorated{name=debug, debuggable=true, testCoverageEnabled=false, jniDebuggable=false, pseudoLocalesEnabled=false, renderscriptDebuggable=false, renderscriptOptimLevel=3, versionNameSuffix=null, minifyEnabled=false, zipAlignEnabled=true, signingConfig=SigningConfig_Decorated{name=debug, storeFile=C:\Users\srima\.android\debug.keystore, storePassword=android, keyAlias=AndroidDebugKey, keyPassword=android, storeType=C:\Users\srima\.android\debug.keystore}, embedMicroApp=false, mBuildConfigFields={CRASHLYTICS_ACTIVATED=com.android.builder.internal.ClassFieldImpl@21c388c0, DEBUG_LOG=com.android.builder.internal.ClassFieldImpl@b871c81e}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}}.
<a href="openFile:D:\android_studio_project\buddy\app\build.gradle">Open File</a>

**Comment by benoitletondor** [comment]
Hi there,

Indeed you need to provide with 3 files containing private service ids for the app to work: `batch.gradle`, `fabric.properties` and `iap.gradle`. You can find a sample for each file into the repo: https://github.com/benoitletondor/EasyBudget/tree/master/Android/EasyBudget/app

Hope it helps.
