### ISSUE TITLE
Error while Opening in Android Studio

### ISSUE THREAD

**Issue by atharvanvaidya** [benoitletondor/EasyBudget#3]
Error:(30, 0) Could not read script 'C:\Users\Lenovo\AndroidStudioProjects\EasyBudget\Android\EasyBudget\app\batch.gradle' as it does not exist.
<a href="openFile:C:\Users\Lenovo\AndroidStudioProjects\EasyBudget\Android\EasyBudget\app\build.gradle">Open File</a>

**Comment by benoitletondor** [comment]
Hi there,

You are indeed in charge of providing 3 files:

- `batch.gradle` which contains the API keys for Batch SDK
- `iap.gradle` which contains the Google Play license key 
- `fabric.properties` which contains the Fabric API data

All of those are under `/app` and a sample is provided for each one. 

Good luck

**Comment by atharvanvaidya** [comment]
So that means I need to enter valid values instead of Capitalized letters
in those files and change the name of the file by removing .sample??

**Comment by benoitletondor** [comment]
Yes, that's exactly what you need to do ;)

**Comment by atharvanvaidya** [comment]
Okay. Can you please help me in replacing those values??....From where to
fill those values?

**Comment by benoitletondor** [comment]
If you take a look at my first answer you'll see where I got them. Just in case:

- `batch.gradle` which contains the API keys for Batch SDK -> [batch.com](https://batch.com)
- `iap.gradle` which contains the Google Play license key -> [Play Services billing](https://developer.android.com/google/play/billing/index.html)
- `fabric.properties` which contains the Fabric API data -> [fabric.io](https://get.fabric.io/)

Good luck!
