### ISSUE TITLE
Sync DB between devices 

### ISSUE THREAD

**Issue by gitty8** [benoitletondor/EasyBudget#5]
I would like to sync the db between 3 android devices with Resilio. Is it possible? If so, which file is the stored db?

**Comment by benoitletondor** [comment]
Hi @gitty8,

Right now, sync hasn't been tested at all and the app needs some changes to be able to do that. If you feel like getting your hands dirty feel free to jump into the code and check it.

The data is stored in an SQLite DB but you will also want to save the preferences which are not, so there's work to do.

I'm keeping the issue open as a reminder that this is a requested feature.

**Comment by benoitletondor** [comment]
This has been implemented in the form of using a synced online DB for Pro online accounts in #17 and will be included in the next major release
