### ISSUE TITLE
batch.gradle and iap.gradle does not exist.

### ISSUE THREAD

**Issue by feelinc** [benoitletondor/EasyBudget#6]
Hi,

Steps :
1) Cloning the repo.
2) Open the project using Android Studio 3.0.1.

Grandle Sync error :

Error:Could not read script '/path/to/project/EasyBudget/Android/EasyBudget/app/batch.gradle' as it does not exist.

Are there something missing in the repo?

Thanks.

**Comment by javajudt** [comment]
I am seeing this error too. Same version of Android Studio.

**Comment by javajudt** [comment]
@feelinc, I looked at past issues and found out you must provide these files. See #2, #3.

**Comment by benoitletondor** [comment]
Hi there,

You are indeed in charge of providing 3 files:

- `batch.gradle` which contains the API keys for Batch SDK
- `iap.gradle` which contains the Google Play license key 
- `fabric.properties` which contains the Fabric API data

All of those are under `/app` and a sample is provided for each one. 

Good luck

PS: Feel free to investigate more than 3 seconds on your own before creating an issue on a repo. Looking at the error and going into the repository reported by the error would have been much more productive than waiting for a response here ;)

**Comment by benoitletondor** [comment]
Another reminder: If you plan to copy the app or a part of the app for your own personal project, feel free to do so but 2 reminders:
- Everything related to the EasyBudget name and brand is under copyright (includes the name, colors and images)
- If you use any part of this code into your own app, you should include a mention according to the apache 2 license

**Comment by feelinc** [comment]
Thanks for the info.

I was trying look for the suspected missing files using my editor file search, but not found, perhaps I'm typing them all wrong in the first place. So I might spent more than 3 seconds to search the files before creating this issue.

**Comment by feelinc** [comment]
Also, I'm not sure what the reason you put the "Another reminder" here, because you can put it in the repo README if you really want to make very clear.

Of you don't want someone creating issue here, I think best if you close this repo.

PS : I had deleting this repo in my computer yesterday.

**Comment by benoitletondor** [comment]
I'm closing this issue for now, no need to go further into it. 

Good luck
