### ISSUE TITLE
Could not read script

### ISSUE THREAD

**Issue by pablopy** [benoitletondor/EasyBudget#8]
I'm getting this error when I compile the application. What could it be?

Could not read script 'C:\Users\HP\Documents\budget\EasyBudget-master\Android\EasyBudget\app\batch.gradle' as it does not exist.

**Comment by benoitletondor** [comment]
Hi there,

You are indeed in charge of providing 3 files:

- `batch.gradle` which contains the API keys for Batch SDK
- `iap.gradle` which contains the Google Play license key 
- `fabric.properties` which contains the Fabric API data

All of those are under `/app` and a sample is provided for each one. 

Good luck

PS: Feel free to investigate more than 3 seconds on your own before creating an issue on a repo. Looking at the error and going into the repository reported by the error would have been much more productive than waiting for a response here ;) 

PS-2: If you plan to copy the app or a part of the app for your own personal project, feel free to do so but 2 reminders:
- Everything related to the EasyBudget name and brand is under copyright (includes the name, colors and images)
- If you use any part of this code into your own app, you should include a mention according to the apache 2 license
